<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.5</version>
        <relativePath/>
    </parent>
    <groupId>com.jevsuite</groupId>
    <artifactId>jev-suite</artifactId>
    <version>0.1.0</version>
    <packaging>pom</packaging>
    <modules>
        <module>jev-kit</module>
        <module>jev-proof</module>
        <module>jev-fit</module>
        <module>jev-fidelity</module>
        <module>jev-rental</module>
    </modules>
    <properties>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>
</project>
